name: Main Branch Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setEnv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set version
        run: echo "VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties)" >> $GITHUB_ENV
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JRE on Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.JRE_ARTIFACTS_TOKEN }}
        run: ./gradlew build
      - name: Build JRE on Windows
        if: matrix.os == 'windows-latest'
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.JRE_ARTIFACTS_TOKEN }}
        run: ./gradlew.bat build
      - name: Build JRE on macOS
        if: matrix.os == 'macOS-latest'
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.JRE_ARTIFACTS_TOKEN }}
        run: ./gradlew build
      - name: Archive Linux Artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          # Todo - Include version once job-level environment variable support is fixed.
          name: ballerina-jre-linux-${{VERSION}}.zip
          path: build/distributions/ballerina-jre-linux.zip
      - name: Archive Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          # Todo - Include version once job-level environment variable support is fixed.
          name: ballerina-jre-windows-${{VERSION}}.zip
          path: build/distributions/ballerina-jre-windows.zip
      - name: Archive MacOS Artifacts
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v2
        with:
          # Todo - Include version once job-level environment variable support is fixed.
          name: ballerina-jre-macos-${{VERSION}}.zip
          path: build/distributions/ballerina-jre-macos.zip
