name: Publish release

on:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  release_assets:
    name: Release assets
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set env-variable for releasse version
        run: echo "VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | cut -d- -f1)" >> $GITHUB_ENV
      - name: Build JRE on Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          packageUser: ${{ secrets.GITHUB_USERNAME }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build
      - name: Build JRE on Windows
        if: matrix.os == 'windows-latest'
        env:
          packageUser: ${{ secrets.GITHUB_USERNAME }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat build
      - name: Build JRE on macOS
        if: matrix.os == 'macOS-latest'
        env:
          packageUser: ${{ secrets.GITHUB_USERNAME }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build
      - name: Upload linux release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-${{ matrix.os }}-${VERSION}.zip
          asset_path: build/build/distributions/ballerina-${{ matrix.os }}-${VERSION}.zip
          asset_content_type: application/octet-stream
