name: Publish release

on:
  workflow_dispatch:

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  release_assets:
    name: Release assets
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build JRE on Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.JRE_ARTIFACTS_TOKEN }}
        run: ./gradlew build
      - name: Build JRE on Windows
        if: matrix.os == 'windows-latest'
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.JRE_ARTIFACTS_TOKEN }}
        run: ./gradlew.bat build
      - name: Build JRE on macOS
        if: matrix.os == 'macOS-latest'
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.JRE_ARTIFACTS_TOKEN }}
        run: ./gradlew build
      - name: Upload linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-linux-0.7.24-SNAPSHOT.zip
          asset_path: build/distributions/ballerina-jre-linux-0.7.24-SNAPSHOT.zip
          asset_content_type: application/octet-stream
      - name: Upload windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          aasset_name: ballerina-jre-windows-0.7.24-SNAPSHOT.zip
          asset_path: build/distributions/ballerina-jre-windows-0.7.24-SNAPSHOT.zip
          asset_content_type: application/octet-stream
      - name: Upload macOS artifacts
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_name: ballerina-jre-macos-0.7.24-SNAPSHOT.zip
          asset_path: build/distributions/ballerina-jre-macos-0.7.24-SNAPSHOT.zip
          asset_content_type: application/octet-stream
